# Generated by Django 5.2.4 on 2025-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userAlley',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='弄'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userBirthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userCountry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userFirstName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓氏'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userFloor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='樓'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userFullName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='全名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userIdentityCard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身分証號'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userLane',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='巷'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userLastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userLocalPhone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市話'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userMobilePhone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userNeighbor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鄰'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userPublicOrPrivate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身分別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userRole',
            field=models.PositiveIntegerField(default=0, verbose_name='權限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userSection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='段'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userStreet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='街路'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userTownship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鄉鎮'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userVillage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='村里'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userWorkArea',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工作轄區'),
        ),
    ]
