# Generated by Django 5.2.4 on 2025-07-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_useralley_customuser_userbirthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
