# Generated by Django 5.2.4 on 2025-07-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_yfcase_yfcasecasestatus_and_more'),
        ('users', '0003_remove_customuser_department_remove_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.city', verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userTownship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.township', verbose_name='鄉鎮'),
        ),
    ]
