# Generated by Django 5.2.4 on 2025-07-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='縣市名稱')),
            ],
            options={
                'verbose_name': '縣市',
                'verbose_name_plural': '縣市',
            },
        ),
        migrations.CreateModel(
            name='YfCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yfcaseCaseNumber', models.CharField(max_length=100, verbose_name='案號(*)')),
                ('yfcaseCompany', models.CharField(blank=True, max_length=50, null=True, verbose_name='所屬公司')),
                ('yfcaseBigSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='段號')),
                ('yfcaseSmallSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='小段')),
                ('yfcaseVillage', models.CharField(blank=True, max_length=100, null=True, verbose_name='村里')),
                ('yfcaseNeighbor', models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰')),
                ('yfcaseStreet', models.CharField(blank=True, max_length=100, null=True, verbose_name='街路')),
                ('yfcaseSection', models.CharField(blank=True, max_length=100, null=True, verbose_name='段')),
                ('yfcaseLane', models.CharField(blank=True, max_length=100, null=True, verbose_name='巷')),
                ('yfcaseAlley', models.CharField(blank=True, max_length=100, null=True, verbose_name='弄')),
                ('yfcaseNumber', models.CharField(max_length=100, null=True, verbose_name='號')),
                ('yfcaseFloor', models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)')),
                ('yfcaseCityWithTownship', models.CharField(blank=True, max_length=20, null=True, verbose_name='縣市鄉鎮')),
                ('yfcaseCaseStatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='案件狀態')),
                ('yfcaseUpdated', models.DateTimeField(auto_now=True, verbose_name='案件最後更新時間')),
                ('yfcaseTimestamp', models.DateTimeField(auto_now_add=True, verbose_name='案件建立時間')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-yfcaseTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='鄉鎮區里名稱')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.city', verbose_name='所屬縣市')),
            ],
            options={
                'verbose_name': '鄉鎮區里',
                'verbose_name_plural': '鄉鎮區里',
            },
        ),
    ]
