# Generated by Django 5.2.4 on 2025-07-26 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='區域負責人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.city', verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseTownship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.township', verbose_name='鄉鎮區里'),
        ),
        migrations.AlterUniqueTogether(
            name='township',
            unique_together={('name', 'city')},
        ),
    ]
