# Generated by Django 5.2.4 on 2025-07-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseCityWithTownship',
        ),
    ]
