# Generated by Django 5.2.4 on 2025-07-26 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_yfcase_yfcasecitywithtownship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCaseStatus',
            field=models.CharField(default='test', max_length=10, verbose_name='案件狀態'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCompany',
            field=models.CharField(default=1, max_length=50, verbose_name='所屬公司'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='號'),
            preserve_default=False,
        ),
    ]
