# Generated by Django 5.2.3 on 2025-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_yfcase_yfcasecasestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseTownship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鄉鎮區里'),
        ),
    ]
