# Generated by Django 5.2.3 on 2025-07-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_yfcase_yfcasecity_alter_yfcase_yfcasetownship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.city', verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseTownship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.township', verbose_name='鄉鎮區里'),
        ),
    ]
